name: Articles Build CI

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      pr_url:
        required: true
        type: string

jobs:
  build-article:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/word-coins/latex-build:latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check exist main.md file
        shell: bash
        run: |
          cd ${{ inputs.branch_name }}
          if [ -f ./main.md ]; then
            echo "exist=true" >> $GITHUB_OUTPUT
          fi
        id: main_md

      - name: convert markdown to latex
        if: steps.main_md.outputs.exist == 'true'
        run: |
          cd ${{ inputs.branch_name }}
          make pandoc

      - name: build articles branch
        run: |
          ARTICLE_NAME=$(echo '${{ inputs.branch_name }}' | awk -F '/' '{print $2}')
          echo "article_name=$ARTICLE_NAME" >> $GITHUB_OUTPUT
          cd ${{ inputs.branch_name }}
          WORD_FONT=sourcehan-jp make
          mv main.pdf "$ARTICLE_NAME.pdf"
        id: build

      - name: upload artifact to github
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.article_name }}.pdf
          path: ${{ inputs.branch_name }}/{{ $steps.build.outputs.article_name }}.pdf
          retention-days: 3 # 3日くらいあったらみんなダウンロードして確認しているはず
        id: upload-artifact

      - name: setup the GitHub CLI
        # https://github.com/cli/cli/blob/trunk/docs/install_linux.md
        run: |
          (type -p wget >/dev/null || (apt update && apt-get install wget -y)) \
            && mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && apt update \
            && apt install gh -y

      - name: Post a comment
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          message="[${{ steps.build.outputs.article_name }}.pdf](${{ steps.upload-artifact.outputs.artifact-url }})"
          set +e
          echo -e $message | gh pr comment "${{inputs.pr_url }}" -F "-" --edit-last
          if [ $? -ne 0 ]; then
            # コメントが存在しないなどにより失敗した場合は新しく投稿する
            echo -e $message | gh pr comment "${{inputs.pr_url }}" -F "-"
          fi
          set -e

